# Generated by Django 5.0.2 on 2024-02-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedBack',
        ),
    ]
