# Generated by Django 5.0.2 on 2024-02-27 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fn_app', '0002_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('remarks', models.TextField(null=True)),
                ('rating', models.CharField(max_length=2)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
