# Generated by Django 5.0.2 on 2024-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('event_venue', models.CharField(default='Auditorium', max_length=80)),
                ('event_date', models.TextField()),
                ('evnt_gallery', models.FileField(default='', upload_to='fn_app/event_gallery')),
            ],
        ),
    ]
