# Generated by Django 5.0.2 on 2024-03-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0005_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
