# Generated by Django 5.0.2 on 2024-03-04 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0006_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('event_venue', models.CharField(default='Auditorium', max_length=80)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_description', models.TextField()),
                ('evnt_gallery', models.FileField(default='', upload_to='fn_app/event_gallery')),
            ],
        ),
    ]
