# Generated by Django 5.0.2 on 2024-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(max_length=100)),
                ('d_name', models.TextField(max_length=100)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_phone', models.CharField(max_length=10)),
                ('d_qualificatiion', models.TextField(max_length=100)),
                ('d_state', models.TextField(max_length=20)),
                ('d_city', models.TextField(max_length=20)),
                ('d_gender', models.CharField(max_length=10)),
                ('d_skill', models.TextField(max_length=50)),
                ('d_about', models.TextField(max_length=100)),
            ],
        ),
    ]
