# Generated by Django 5.0.2 on 2024-03-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0012_designer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designer',
        ),
    ]
