# Generated by Django 5.0.2 on 2024-03-05 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0013_delete_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('d_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('d_password', models.CharField(max_length=20)),
                ('d_name', models.CharField(max_length=40)),
                ('d_mail', models.EmailField(max_length=254, unique=True)),
                ('d_phone', models.CharField(max_length=11)),
                ('d_qualification', models.TextField()),
                ('d_state', models.CharField(max_length=20)),
                ('d_city', models.CharField(max_length=20)),
                ('d_gender', models.CharField(max_length=6)),
                ('d_skills', models.CharField(max_length=100)),
                ('d_about', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
