# Generated by Django 5.0.3 on 2024-03-08 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0014_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('u_password', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=40)),
                ('u_mail', models.EmailField(max_length=254, unique=True)),
                ('u_gender', models.CharField(max_length=6)),
                ('u_phone', models.CharField(max_length=11)),
                ('u_address', models.TextField()),
                ('u_city', models.CharField(max_length=20)),
                ('u_state', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
