# Generated by Django 5.0.3 on 2024-03-15 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0015_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('seats_available', models.CharField(max_length=50)),
                ('mailing_link', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=30)),
                ('work_profile', models.CharField(max_length=100)),
                ('min_qual', models.CharField(max_length=40)),
                ('job_location', models.CharField(max_length=30)),
                ('age_req', models.CharField(max_length=2)),
                ('last_date', models.DateField()),
                ('salary_pkg', models.CharField(max_length=6)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fn_app.designer')),
            ],
        ),
    ]
