# Generated by Django 5.0.3 on 2024-04-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0016_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('client', models.CharField(max_length=20, null=True)),
                ('photo', models.FileField(default='', upload_to='fn_app/designer_pics')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fn_app.designer')),
            ],
        ),
    ]
