# Generated by Django 5.0.3 on 2024-04-10 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0017_designerwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsTricks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fn_app.designer')),
            ],
        ),
    ]
