# Generated by Django 5.0.3 on 2024-04-15 10:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0018_tipstricks'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_content', models.TextField()),
                ('photo', models.FileField(default='', upload_to='fn_app/news_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message_text', models.TextField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reciever_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fn_app.designer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fn_app.user')),
            ],
        ),
    ]
