# Generated by Django 5.0.3 on 2024-04-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0020_news_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
