# Generated by Django 5.0.3 on 2024-04-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0022_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
