# Generated by Django 5.0.3 on 2024-04-25 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0023_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fn_app.designer')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fn_app.user')),
            ],
        ),
    ]
