# Generated by Django 5.0.3 on 2024-05-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0024_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='designer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.BooleanField(default=True),
        ),
    ]
