# Generated by Django 5.0.3 on 2024-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0025_designer_designer_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='d_pic',
            field=models.FileField(default='', upload_to='Designers/'),
        ),
        migrations.AddField(
            model_name='user',
            name='u_pic',
            field=models.FileField(default='', upload_to='Users/'),
        ),
    ]
