# Generated by Django 5.0.3 on 2024-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0026_designer_d_pic_user_u_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='designer',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_text',
        ),
        migrations.AddField(
            model_name='message',
            name='designer_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
