# Generated by Django 5.0.3 on 2024-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0027_rename_receiver_id_message_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='d_qualification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='designer',
            name='d_skills',
            field=models.CharField(max_length=50),
        ),
    ]
