# Generated by Django 5.0.3 on 2024-05-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0028_alter_designer_d_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipstricks',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
