# Generated by Django 5.0.3 on 2024-05-21 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_app', '0029_alter_tipstricks_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
